# Generated by Django 5.0.6 on 2024-07-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('description', models.CharField(max_length=1000)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('transmission_type', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('is_sold', models.BooleanField(default=False)),
            ],
        ),
    ]
