# Generated by Django 5.0.6 on 2024-07-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0002_alter_car_transmission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(null=True),
        ),
    ]
