# Generated by Django 5.0.6 on 2024-07-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0005_rename_image_carimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('PETROL', 'PETROL'), ('DIESEL', 'DIESEL'), ('ELECTRIC', 'ELECTRIC'), ('HYBRID', 'HYBRID')], default='PETROL', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('TRUCK', 'TRUCK'), ('BUS', 'BUS'), ('BAKKIE', 'BAKKIE'), ('SEDAN', 'SEDAN'), ('HATCHBACK', 'HATCHBACK')], default='TRUCK', max_length=50),
        ),
    ]
